apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders-api
          image: arjanaswal/node-kubernetes-orders-service:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: SERVICE
              value: 'orders'
            - name: NODE_ENV
              value: 'development'
            - name: PORT
              value: '3003'
            - name: JWT_SECRET
              value: 'secret'
            - name: POSTGRES_URL
              value: postgres://postgres:postgres@postgresql-service.default:5432/postgres
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq-service.default:5672
