apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products-api
          image: arjanaswal/node-kubernetes-products-service:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: SERVICE
              value: 'products'
            - name: NODE_ENV
              value: 'development'
            - name: PORT
              value: '3002'
            - name: JWT_SECRET
              value: 'secret'
            - name: POSTGRES_URL
              value: postgres://postgres:postgres@postgresql-service.default:5432/postgres
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq-service.default:5672
